# Generated by Django 5.2.1 on 2025-05-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
